# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae4e9df5522b684905411c5ad2e544207c96314b7aa6f6671ea920673888d8467fbab120a427c6f36651e68c5b53c8f18e8b0e977ba5fce907dc89c3c7a89169

test:
  secret_key_base: ede4cbe2d2610aa6aefeb6a26630c250a31c5be62ea0a9fd49d5f7a00a86069a4913a64e17b232592b24b2afee2a730a6c857657d3ae7418797d1e167373626f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
